project_id = "watxvzoolmfjfijrgcvq"

[functions.cancel-user-invite]
verify_jwt = false

[functions.daily-message]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.sync-stripe-tier]
verify_jwt = false

[functions.get-subscription-details]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = false

[functions.send-file-share-email]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.google-drive-callback]
verify_jwt = false

[functions.sync-to-google-drive]
verify_jwt = false

[functions.google-drive-folders]
verify_jwt = false
