project_id = "watxvzoolmfjfijrgcvq"

[functions.analyze-plan]
verify_jwt = true

[functions.backfill-timecard-costcodes]
verify_jwt = true

[functions.send-overdue-bill-notifications]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false

[functions.send-rfp-invite]
verify_jwt = false

[functions.send-vendor-invite]
verify_jwt = false
